### ISSUE TITLE
Update documentation about registering type with Arrow

### ISSUE THREAD

**Issue by giordano** [JuliaEcosystem/PackageAnalyzer.jl#52]
With latest Arrow version I get
```
┌ Warning: Arrow.ArrowTypes.registertype! is deprecated in favor of defining `ArrowTypes.ArrowType`, `ArrowTypes.arrowname`, and `ArrowTypes.JuliaType`; see their docs for more information on how to migrate
└ @ Arrow.ArrowTypes ~/.julia/packages/Arrow/OiknN/src/arrowtypes.jl:375
```

**Comment by ericphanson** [comment]
The new methods are pretty simple too: https://arrow.juliadata.org/dev/manual/#Custom-types. I think ArrowTypes is being split out as a separate lightweight package so we could consider depending on it to define the methods, or just update the docs.

**Comment by giordano** [comment]
We don't depend on `Arrow` in this package, so we only need to update the documentation for the new syntax :slightly_smiling_face:
