### ISSUE TITLE
Update dependencies to prevent environment-wide downgrades

### ISSUE THREAD

**Issue by zsz00** [JuliaEcosystem/PackageAnalyzer.jl#66]
add PackageAnalyzer

![image](https://user-images.githubusercontent.com/12711073/148764366-687f412b-9da1-49ca-9a05-7d56de08872c.png)

**Comment by giordano** [comment]
Current compat bounds
https://github.com/JuliaEcosystem/PackageAnalyzer.jl/blob/04d4d1756d2a09c21039e0acc01229c207fbbe69/Project.toml#L17-L22
already allows latest versions of all involved packages, I don't think we have to do anything

**Comment by giordano** [comment]
As a side note, I strongly recommend using local environments instead of installing all packages in the global environment.  That'd make package resolution simpler and avoids problems when hundreds of unrelated packages try to find a common set of compatible versions

**Comment by zsz00** [comment]
my version is julia 1.7.1 
why make this downgrades ?

**Comment by giordano** [comment]
I don't know what other packages you have in your global environment :slightly_smiling_face:  Using small global environments + task-specific local environments solve this issue

**Comment by zsz00** [comment]
ok , thks

**Comment by giordano** [comment]
@zsz00 If you update the registry, you should get `Git_jll` v2.34.1 which may resolve conflict with your other packages.

**Comment by zsz00** [comment]
yes, I tried this. It's worked.
