### ISSUE TITLE
Is `documention` a typo ?

### ISSUE THREAD

**Issue by t-bltg** [JuliaEcosystem/PackageAnalyzer.jl#73]
Or is it a new concept ?

https://github.com/JuliaEcosystem/PackageAnalyzer.jl/blob/main/src/PackageAnalyzer.jl#L116-L117

**Comment by ericphanson** [comment]
Typo, lol. PRs appreciated :)

**Comment by t-bltg** [comment]
You never know, it could come from another language from another universe ...
I prefer to ask before making a PR and discover that it was intentional :laughing:
