### ISSUE TITLE
Registered version is very old

### ISSUE THREAD

**Issue by aplavin** [JuliaEcosystem/PackageAnalyzer.jl#75]
Version in Package.toml: 1.0.0
In General: 0.1.0

Can it be updated there?

**Comment by ericphanson** [comment]
I was hoping to land https://github.com/JuliaEcosystem/PackageAnalyzer.jl/pull/71 in the same release, but we could just mark that as 2.0 I guess. Review there would help move it along!

**Comment by ericphanson** [comment]
1.0 is out!
