### ISSUE TITLE
Register Julia 1.3 branch

### ISSUE THREAD

**Issue by ericphanson** [JuliaEcosystem/PackageAnalyzer.jl#81]
@JuliaRegistrator register branch=eph/1.3-support

**Comment by ericphanson** [comment]
I'll have to try with LocalRegistry + a manual PR

**Comment by giordano** [comment]
Register 0.2.0, compatible _only_ with 1.3-1.5?

**Comment by ericphanson** [comment]
Hm, yeah that would work I think

**Comment by ericphanson** [comment]
@JuliaRegistrator register branch=eph/1.3-support
