### ISSUE TITLE
PackageAnalyzer/LicenseCheck reliably crashes on Apple Silicon, but only in VSCode

### ISSUE THREAD

**Issue by SamuraiAku** [JuliaEcosystem/PackageAnalyzer.jl#97]
At least it reliably crashes for me:

```julia
julia> versioninfo()
Julia Version 1.10.1
Commit 7790d6f0641 (2024-02-13 20:41 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
Threads: 4 default, 0 interactive, 2 GC (on 4 virtual cores)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 4
```

The problem is some kind of segfault when PackageAnalyzer invokes LicenseChecker.jl . I know this because I get the same behavior when I try to use LicenseCheck directly.

This problem does not happen when I invoke julia from the terminal, only when launching julia within VSCode using julia-vscode.

```
VSCode version info

Version: 1.86.2 (Universal)
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:42:13.651Z (1 wk ago)
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.3.0
```

julia-vscode version 1.73.2

I can't give you a stack trace because VScode instantly closes the terminal window on the crash and I can't figure out a way to save it. This is a [known issue](https://github.com/julia-vscode/julia-vscode/issues/1788)

This is probably related/the same as #77 , but I wanted to document my environment conditions.

**Comment by ericphanson** [comment]
thanks for the report; let's close in favor of https://github.com/ericphanson/LicenseCheck.jl/issues/11
